version: '3.8'

services:
  backend:
    build: .
    container_name: protaskx-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

  mongodb:
    image: mongo:6
    container_name: protaskx-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: protaskx-redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
